version: '3.2'

services:
  php:
    build:
      context: docker
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./:/srv/symfony
    ports:
      - 8000:8000
    logging:
      driver: "json-file"
      options:
        max-size: "512k"
        max-file: "10"

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=${DATABASE_DB}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    ports:
      - 5432:5432
    logging:
      driver: "json-file"
      options:
        max-size: "512k"
        max-file: "10"

volumes:
  db-data: {}
